#!/bin/sh

# autopkgtest check: Build a trivial project that uses the
# find_package(CoprightTest) macro, and verify that the resulting test binary
# behaves as expected.
# (C) 2016 Canonical Ltd.
# Author: James Henstridge <james.henstridge@canonical.com>

set -ep

builddir=$(mktemp --tmpdir="${AUTOPKGTEST_TMP:-/tmp}" -d)
trap "rm -rf $builddir" 0 INT QUIT ABRT PIPE TERM
builddir=/tmp/build

srcdir="`pwd`/examples/copyrighttest-demo"

cd $builddir
cmake $srcdir
! ctest -R must_fail_1 must_fail_1_test
! ctest -R must_fail_2
! ctest -R must_fail_3
! ctest -R must_fail_4
ctest -R must_succeed_1
ctest -R must_succeed_2
ctest -R must_succeed_3
