#!/bin/bash

# autopkgtest check: Build a trivial project that uses the
# find_package(GSettings) macro.
# (C) 2017 Canonical Ltd.

set -euo pipefail
IFS=$'\n\t'

tempdir=$(mktemp --tmpdir="${AUTOPKGTEST_TMP:-/tmp}" -d)
trap "rm -rf $tempdir" 0 INT QUIT ABRT PIPE TERM

demodir="$(pwd)/examples/gsettings-demo"
srcdir="${tempdir}/source"
bindir="${tempdir}/build"
installdir="${tempdir}/install"

cp -r "${demodir}" "${srcdir}"
mkdir -p "${bindir}"

# Move into bindir temporarily
(
  cd "${bindir}"
  cmake -DCMAKE_INSTALL_PREFIX="${installdir}" "${srcdir}"
  make
  make install
)
